# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '网络监测' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 网络监测
  pod 'AFNetworking' 
  target '网络监测Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '网络监测UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
